import "./globals.css";
import { Maven_Pro } from "next/font/google";
import Header from "@/Components/Header/Header";
import NavBar from "@/Components/NavBar/NavBar";
const Maven = Maven_Pro({ subsets: ["latin"], weight: ["400", "500", "600"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={Maven.className} lang="en">
      <body>
        <Header />
        {children}
        <NavBar />
      </body>
    </html>
  );
}
