import "./globals.css";
import { Maven_Pro } from "next/font/google";

const Maven = Maven_Pro({ subsets: ["latin"], weight: ["400", "500", "600"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={Maven.className} lang="en">
      <body>{children}</body>
    </html>
  );
}
