import "./globals.css";
import { Noto_Sans } from "next/font/google";

const Noto = Noto_Sans({ subsets: ["latin"], weight: ["400", "500", "600"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={Noto.className} lang="en">
      <body className="bg-primary-bg h-screen w-screen">{children}</body>
    </html>
  );
}
